ArangoDB on K8s

diff --git a/assignment_3/Dockerfiles/build-all b/assignment_3/Dockerfiles/build-all
--- a/assignment_3/Dockerfiles/build-all
+++ b/assignment_3/Dockerfiles/build-all
@@ -2,6 +2,12 @@
 
 set -e
 
+# Check if docker is installed
+if ! [ -x "$(command -v docker)" ]; then
+  echo 'Error: docker is not installed.' >&2
+  exit 1
+fi
+
 cd "$(dirname "$0")"
 
 for file in $(ls *.Dockerfile); do
